FROM node:20.9

# Declare build arguments
ARG CLOUDINARY_API_SECRET
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_CLOUDINARY_API_SECRET
ARG BASEURL
ARG FRONTEND_URL
ARG STRIPE_WEBHOOK_SECRET
ARG STRIPE_SECRET_KEY
ARG STRIPE_PUBLISHABLE_KEY

# Set environment variables
ENV CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ENV NEXT_PUBLIC_CLOUDINARY_API_SECRET=$NEXT_PUBLIC_CLOUDINARY_API_SECRET
ENV BASEURL=$BASEURL
ENV FRONTEND_URL=$FRONTEND_URL
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY

WORKDIR /app

COPY package.json .
RUN npm config set registry https://registry.npmjs.org/ && \
    npm install --legacy-peer-deps --fetch-retries=5 --fetch-retry-mintimeout=20000

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]